@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
@x64\Debug\tests.exe | findstr /V /C:"0 failure" | findstr /R /V "^$"
@echo | more | time | find "current"
